# Generated by Django 5.0.4 on 2024-05-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0003_answer_rating_delete_answerrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
    ]
