# Generated by Django 5.0.6 on 2024-05-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0005_answer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='anonymous',
        ),
    ]
