# Generated by Django 5.0.6 on 2024-05-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0007_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
    ]
