# Generated by Django 5.0.6 on 2024-05-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0008_remove_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=30),
        ),
    ]
