name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]  # Doit correspondre à votre Pipfile

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Pipenv
      run: pip install pipenv
      
    - name: Install Dependencies
      run: |
        pipenv --python ${{ matrix.python-version }}
        pipenv install --dev
      
    - name: Run Tests
      run: |
        pipenv run python manage.py test
